### ISSUE TITLE
Error opening image

### ISSUE THREAD

**Issue by vaskark** [deviantfero/wpgtk#305]
```
Traceback (most recent call last):
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/gui/theme_picker.py", line 135, in on_add_clicked
    themer.create_theme(f)
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/data/themer.py", line 24, in create_theme
    return color.get_color_list(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/data/color.py", line 36, in get_color_list
    is_new = not os.path.isfile(files.get_cache_path(filename))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/data/files.py", line 79, in get_cache_path
    if __check_is_pywal16cols():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/data/files.py", line 30, in __check_is_pywal16cols
    if wal_backend_version[i] > pywal_archived_version[i]:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'tuple' and 'int'
```

I'm using the latest git. The usual wpgtk from pip doesn't have this error.
Thanks.

Ubuntu 24.04

**Comment by kleshas** [comment]
Same.  arch

**Comment by chrisJuresh** [comment]
Same on arch

**Comment by deviantfero** [comment]
looking into this

**Comment by deviantfero** [comment]
fixed, both on -git and on the latest tag

**Comment by vaskark** [comment]
Still getting the same kind of error. Now on pip regular too as well as latest git:

```
Traceback (most recent call last):
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/gui/color_grid.py", line 306, in combo_box_change
    self.render_theme()
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/gui/color_grid.py", line 170, in render_theme
    self.color_list = color.get_color_list(self.selected_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/data/color.py", line 36, in get_color_list
    is_new = not os.path.isfile(files.get_cache_path(filename))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/data/files.py", line 84, in get_cache_path
    return join(*filename)
           ^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not bool
```
Thanks for looking into this. 
On Ubuntu 24.10.
